<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\User;

class UserTest extends TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = factory(User::class)->create();


        $this->actingAs($user, 'api');
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {


        $this->assertTrue(true);

//        $response = $this->json('GET', 'api/restaurants');
//
//        $response
//            ->assertStatus(200);
//
//        $response = $this->json('GET', 'api/categories');
//
//        $response
//            ->assertStatus(200);
//
//        $response = $this->json('GET', 'api/restaurants/1');
//
//        $response
//            ->assertStatus(200);
//
//        $response = $this->json('POST', 'api/categories', ['name'=>'just the way you feel']);
//
//        $response
//            ->assertStatus(201);




    }
}
